dist: trusty
os: linux
language: cpp
sudo: required

compiler:
    - gcc
    - clang

install:
    - if [ "$CXX" = "g++" ]; then export CC="gcc-7" CXX="g++-7"; fi
    - if [ "$CXX" = "clang++" ]; then export CC="clang-5.0" CXX="clang++-5.0"; fi
    - cd ${TRAVIS_BUILD_DIR}
    - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
    - tar xf lcov_1.13.orig.tar.gz
    - sudo make -C lcov-1.13/ install
    - gem install coveralls-lcov

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - llvm-toolchain-trusty-5.0
            - george-edison55-precise-backports
        packages:
            - gcc-7
            - g++-7
            - clang-5.0
            - clang++-5.0
            - llvm-5.0-dev
            - clang-format
            - libopencv-dev
            - libgtest-dev
            - cmake
            - cmake-data
            - gnuplot
#            - lcov
#            - libboost-all-dev

before_script:
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

script: 
    - (cd .. && exec find regionalizer -iname *.hpp -o -iname *.cpp | xargs clang-format -i -style=file)
    - git status
    - ${CC} -v
    - ${CXX} -v
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTS=ON ..
    - cmake -DBUILD_TESTS=ON ..
    - make VERBOSE=1
    - make test ARGS="-V"

after_success:
    - cd ${TRAVIS_BUILD_DIR} 
    - lcov --directory . --capture --output-file coverage.info
    - lcov --base-directory . --capture --output-file coverage.info
    - lcov --directory build --capture --output-file coverage.info
    - lcov --base-directory build --capture --output-file coverage.info
    - cd build
    - make clean
    - cmake -DBUILD_TESTS=ON ..
    - make
    - make test ARGS="-V"
    - cd -
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info 'test/*' '/usr/*' --output-file coverage.info
    - lcov --list coverage.info
      #    - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
    - coveralls-lcov coverage.info
